prometheus:
  enabled: true
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
      - job_name: kminion-metrics
        scrape_interval: 10s
        scrape_timeout:  5s
        metrics_path: "/metrics"
        static_configs:
        - targets:
          - apk-kminion:8080
      - job_name: zookeeper
        scrape_interval: 10s
        scrape_timeout:  5s
        metrics_path: "/metrics"
        static_configs:
        - targets:
          - apk-zookeeper-metrics:9141
