# Default values for monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

grafana:
  enabled: true
  admin:
    user: admin
    password: admin

  service:
    type: LoadBalancer  # ClusterIP
    clusterIP: ""
    ports:
      grafana: 3000
    nodePorts:
      grafana: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
    externalTrafficPolicy: Cluster
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    apiVersion: ""
    hostname: grafana.local
    path: /
    annotations: {}
    tls: false
    extraHosts: []
    extraPaths: []
    extraTls: []
    secrets: []
    selfSigned: false
    ingressClassName: ""
    ## @param ingress.extraRules Additional rules to be covered with this ingress record
    ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
    ## e.g:
    ## extraRules:
    ## - host: example.local
    ##     http:
    ##       path: /
    ##       backend:
    ##         service:
    ##           name: example-svc
    ##           port:
    ##             name: http
    ##
    extraRules: []



prometheus:
  enabled: true
  prometheus:
    enabled: true
    additionalScrapeConfigs:
      enabled: true
      type: internal
      internal:
        jobList:
        - job_name: kminion-metrics
          scrape_interval: 10s
          scrape_timeout:  5s
          metrics_path: "/metrics"
          static_configs:
          - targets:
            - apk-kminion:8080
        - job_name: zookeeper
          scrape_interval: 10s
          scrape_timeout:  5s
          metrics_path: "/metrics"
          static_configs:
          - targets:
            - apk-zookeeper-metrics:9141
